### ISSUE TITLE
Issue "Lista Movimenti does not exist"

### ISSUE THREAD

**Issue by Nintenking** [Jacotsu/ofxstatement-intesasp#11]
Ciao, questo plugin sarebbe manna dal cielo per me, ma sto riscontrando questo errore quando provo ad eseguire il comando.
Sapete da cosa possa essere dato?

`nintenking@DESKTOP-S4DL8PS:/mnt/c/users/Oscar/downloads$ ofxstatement -d convert -t IntesaSP lista_completa_19092024.xlsx Movimenti.ofx
DEBUG: STREAM b'IHDR' 16 13
DEBUG: STREAM b'pHYs' 41 9
DEBUG: STREAM b'tEXt' 62 25
DEBUG: STREAM b'IDAT' 99 2498
Traceback (most recent call last):
  File "/usr/bin/ofxstatement", line 33, in <module>
    sys.exit(load_entry_point('ofxstatement==0.7.1', 'console_scripts', 'ofxstatement')())
  File "/home/nintenking/.local/lib/python3.10/site-packages/ofxstatement/tool.py", line 221, in run
    return args.func(args)
  File "/home/nintenking/.local/lib/python3.10/site-packages/ofxstatement/tool.py", line 186, in convert
    parser = p.get_parser(args.input)
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/intesaSP.py", line 31, in get_parser
    parser = IntesaSanPaoloXlsxParser(filename)
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/intesaSP.py", line 44, in __init__
    self.statement.account_id = self._get_account_id()
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/intesaSP.py", line 69, in _get_account_id
    return wb['Lista Movimenti']['D8'].value
  File "/usr/lib/python3/dist-packages/openpyxl/workbook/workbook.py", line 288, in __getitem__
    raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet Lista Movimenti does not exist.'`

**Comment by Nintenking** [comment]
Colpa mia ho installato in qualche modo una versione vecchia del plugin, anche se mi ero già messo a debuggare e avevo risolto (l'errore di ieri non ho ben capito perché si presentasse, il mio file .xlsx contiene il foglio 'Lista Operazione' quindi ovviamente non trovava 'Lista Movimenti', ma questo specifico errore non mi si è ripresentato) cambiando alcuni valori hardcoded visto che le funzioni cominciavano a leggere i valori dalle varie colonne partendo dalla riga 20, mentre nel mio file .xlsx specifico gli effettivi valori iniziano da riga 21.

Ma appunto mi sono messo a risolvere un bug che nella versione corrente qui su Github non c'è, quindi chiudo al issue. 
Grazie mille per questo plugin!
