### ISSUE TITLE
Problemi di conversione

### ISSUE THREAD

**Issue by Alfystar** [Jacotsu/ofxstatement-intesasp#3]
Piacere, mi chiamo Emanuele.

Apro questo issue per segnalare il seguente problema di conversione, il file che gli ho dato è stato scaricato direttamente da intesa san paolo, ed ecco il comando incriminato.

```
17:42:29 /media/alfy/Data
└─▶ $ ofxstatement convert -t IntesaSP Movimenti_Conto_23082022\ -\ dal\ 20210223.xlsx Movimenti.ofx
Traceback (most recent call last):
  File "/home/alfy/.local/bin/ofxstatement", line 8, in <module>
    sys.exit(run())
  File "/home/alfy/.local/lib/python3.10/site-packages/ofxstatement/tool.py", line 205, in run
    return args.func(args)
  File "/home/alfy/.local/lib/python3.10/site-packages/ofxstatement/tool.py", line 174, in convert
    parser = p.get_parser(args.input)
  File "/home/alfy/.local/lib/python3.10/site-packages/ofxstatement/plugins/intesaSP.py", line 32, in get_parser
    parser = IntesaSanPaoloXlsxParser(filename)
  File "/home/alfy/.local/lib/python3.10/site-packages/ofxstatement/plugins/intesaSP.py", line 46, in __init__
    self.statement.currency = self._get_currency()
  File "/home/alfy/.local/lib/python3.10/site-packages/ofxstatement/plugins/intesaSP.py", line 76, in _get_currency
    return trans_map[val]
KeyError: 'EUR'
```

Immagino, leggendo anche l'altro problema riportato, che sia semplicemente una chiave di dizionario mancante, attendo speranzoso un fix.

Premetto che ho scaricato da `pip3` il programma, e segnalo pure che tra i pre-requisiti, vi è la presenza di `vim`.

In ultimo, potresti spiegare meglio cosa intendi per BIC/SWIFT che è riportato nel readme? Alla fine ho lasciato i 7-zeri, poichè ho trovato solo codici da 11 caratteri per i BIC, e da 5 Caratteri per ABI e CAB.

Grazie mille in anticipo, resto in attesa di un tuo messaggio.

PS
gran bella idea questo script

**Comment by Alfystar** [comment]
Ho provato a modificare il codice e ho scoperto il problema e un altro problema sulle descrizioni.
Vorrei fare la Pull request, ma penso di far prima mostrandoti qui le 2 funzioni modificate e nel caso ne discutiamo insieme:

A entrambe ho aggiunto che la chiave viene mandata tutta in minuscolo, e quindi ho riscritto le tue Entry di conseguenza, ad esse ho aggiunto anche le mie descrizioni che a quanto pare sono nuove rispetto a quando hai scritto il codice.

Prima funzione:

```
    def _get_currency(self):
        # !!! Write All key value lower case !!!
        trans_map = {'euro': 'EUR',
                     'eur':  'EUR'}
        wb = load_workbook(self.fin)
        val = wb['Lista Movimenti']['D22'].value
        return trans_map[val.lower()]
```
e seconda funzione:
```
    def _get_transaction_type(movimento):
        # OFX Spec https://financialdataexchange.org/ofx
        # 11.4.4.3 Transaction Types Used in <TRNTYPE>
        # !!! Write All key value lower case !!!
        trans_map = {'pagamento pos': 'POS',
                     'pagamento tramite pos': 'POS',
                     'pagamento effettuato su pos estero': 'POS', #TODO: verify
                     'accredito beu con contabile': 'XFER',
                     'canone mensile base e servizi aggiuntivi': 'SRVCHG',
                     'prelievo carta debito su banche del gruppo': 'CASH',
                     'prelievo carta debito su banche italia/sepa': 'CASH',
                     'comm.prelievo carta debito italia/sepa': 'SRVCHG',
                     'commiss. su beu internet banking': 'SRVCHG',
                     'pagamento telefono': 'PAYMENT',
                     'pagamento mav via internet banking': 'PAYMENT',
                     'pagamento bolletta cbill': 'PAYMENT',
                     'beu tramite internet banking': 'PAYMENT',
                     'commissione bolletta cbill': 'SRVCHG',
                     'storno pagamento pos': 'POS',
                     'storno pagamento pos estero': 'POS',
                     'versamento contanti su sportello automatico': 'ATM',
                     'canone annuo o-key sms': 'SRVCHG',
                     'pagamento adue': 'DIRECTDEBIT', #TODO: verify
                     'commissioni e spese adue': 'DIRECTDEBIT', #TODO: verify
                     'donazione preautorizzata ad ente no profit': 'DIRECTDEBIT',
                     'rata bonif. periodico con contab.': 'REPEATPMT',
                     'add. deleghe fisco/inps/regioni': 'DEBIT',
                     'pagamento delega f24 via internet banking': 'PAYMENT',
                     'bonifico in euro verso ue/sepa canale telem.': 'PAYMENT',
                     'accredito bonifico istantaneo': 'DIRECTDEP',
                     'stipendio o pensione': 'CREDIT',  #TODO: verify
                     'pagamenti disposti su circuito fast pay': 'DIRECTDEBIT',  #TODO: verify
                     'ricarica tramite internet:vodafonecard': 'DIRECTDEBIT',  #TODO: verify
                     'pagamento bollettino postale via internet': 'DIRECTDEBIT',  #TODO: verify
                     'ricarica tramite internet:windtre': 'DIRECTDEBIT',  #TODO: verify
                     'commissioni bollettino postale via internet': 'DIRECTDEBIT',  #TODO: verify
                     'pagamento via internet': 'DIRECTDEBIT',  #TODO: verify
                     'commissioni su pagamento via internet': 'DIRECTDEBIT',  #TODO: verify
                     'imposta di bollo e/c e rendiconto': 'DIRECTDEBIT',  #TODO: verify
                     }
        return trans_map[movimento.descrizione.lower()]
```

Su questa seconda ho recuperato le tue chiavi ma onestamente non sono sicurissimo di aver capito bene e messo quelli corretti, te li evidenzio con il TODO e sarei felice di avere un tuo feedback o di parlarne qui.
